require 'jiraService.rb'
require 'jiraServiceMappingRegistry.rb'

module Jira4R::V2
require 'soap/rpc/driver'

class JiraSoapService < ::SOAP::RPC::Driver
  DefaultEndpointUrl = "http://localhost:8080/rpc/soap/jirasoapservice-v2"

  Methods = [
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getServerInfo"),
      "",
      "getServerInfo",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getServerInfoReturn", ["Jira4R::V2::RemoteServerInfo", "http://beans.soap.rpc.jira.atlassian.com", "RemoteServerInfo"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "login"),
      "",
      "login",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "loginReturn", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getUser"),
      "",
      "getUser",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getUserReturn", ["Jira4R::V2::RemoteUser", "http://beans.soap.rpc.jira.atlassian.com", "RemoteUser"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "createUser"),
      "",
      "createUser",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["::SOAP::SOAPString"]],
        ["in", "in3", ["::SOAP::SOAPString"]],
        ["in", "in4", ["::SOAP::SOAPString"]],
        ["retval", "createUserReturn", ["Jira4R::V2::RemoteUser", "http://beans.soap.rpc.jira.atlassian.com", "RemoteUser"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getProject"),
      "",
      "getProject",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getProjectReturn", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getIssue"),
      "",
      "getIssue",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getIssueReturn", ["Jira4R::V2::RemoteIssue", "http://beans.soap.rpc.jira.atlassian.com", "RemoteIssue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "createIssue"),
      "",
      "createIssue",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteIssue", "http://beans.soap.rpc.jira.atlassian.com", "RemoteIssue"]],
        ["retval", "createIssueReturn", ["Jira4R::V2::RemoteIssue", "http://beans.soap.rpc.jira.atlassian.com", "RemoteIssue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getAvailableActions"),
      "",
      "getAvailableActions",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getAvailableActionsReturn", ["Jira4R::V2::RemoteNamedObject[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteNamedObject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getProjects"),
      "",
      "getProjects",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getProjectsReturn", ["Jira4R::V2::RemoteProject[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteProject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "updateIssue"),
      "",
      "updateIssue",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["Jira4R::V2::RemoteFieldValue[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteFieldValue"]],
        ["retval", "updateIssueReturn", ["Jira4R::V2::RemoteIssue", "http://beans.soap.rpc.jira.atlassian.com", "RemoteIssue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getConfiguration"),
      "",
      "getConfiguration",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getConfigurationReturn", ["Jira4R::V2::RemoteConfiguration", "http://beans.soap.rpc.jira.atlassian.com", "RemoteConfiguration"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "updateProject"),
      "",
      "updateProject",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]],
        ["retval", "updateProjectReturn", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getIssueTypes"),
      "",
      "getIssueTypes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getIssueTypesReturn", ["Jira4R::V2::RemoteIssueType[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteIssueType"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getPriorities"),
      "",
      "getPriorities",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getPrioritiesReturn", ["Jira4R::V2::RemotePriority[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemotePriority"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getResolutions"),
      "",
      "getResolutions",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getResolutionsReturn", ["Jira4R::V2::RemoteResolution[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteResolution"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getStatuses"),
      "",
      "getStatuses",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getStatusesReturn", ["Jira4R::V2::RemoteStatus[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteStatus"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getSubTaskIssueTypes"),
      "",
      "getSubTaskIssueTypes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getSubTaskIssueTypesReturn", ["Jira4R::V2::RemoteIssueType[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteIssueType"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getProjectRoles"),
      "",
      "getProjectRoles",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getProjectRolesReturn", ["Jira4R::V2::RemoteProjectRole[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteProjectRole"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getProjectRole"),
      "",
      "getProjectRole",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPLong"]],
        ["retval", "getProjectRoleReturn", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getProjectRoleActors"),
      "",
      "getProjectRoleActors",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["in", "in2", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]],
        ["retval", "getProjectRoleActorsReturn", ["Jira4R::V2::RemoteProjectRoleActors", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRoleActors"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getDefaultRoleActors"),
      "",
      "getDefaultRoleActors",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["retval", "getDefaultRoleActorsReturn", ["Jira4R::V2::RemoteRoleActors", "http://beans.soap.rpc.jira.atlassian.com", "RemoteRoleActors"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "removeAllRoleActorsByNameAndType"),
      "",
      "removeAllRoleActorsByNameAndType",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "removeAllRoleActorsByProject"),
      "",
      "removeAllRoleActorsByProject",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "deleteProjectRole"),
      "",
      "deleteProjectRole",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["in", "in2", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "updateProjectRole"),
      "",
      "updateProjectRole",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "createProjectRole"),
      "",
      "createProjectRole",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["retval", "createProjectRoleReturn", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "isProjectRoleNameUnique"),
      "",
      "isProjectRoleNameUnique",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "isProjectRoleNameUniqueReturn", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "addActorsToProjectRole"),
      "",
      "addActorsToProjectRole",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::C_String[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_xsd_string"]],
        ["in", "in2", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["in", "in3", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]],
        ["in", "in4", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "removeActorsFromProjectRole"),
      "",
      "removeActorsFromProjectRole",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::C_String[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_xsd_string"]],
        ["in", "in2", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["in", "in3", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]],
        ["in", "in4", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "addDefaultActorsToProjectRole"),
      "",
      "addDefaultActorsToProjectRole",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::C_String[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_xsd_string"]],
        ["in", "in2", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["in", "in3", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "removeDefaultActorsFromProjectRole"),
      "",
      "removeDefaultActorsFromProjectRole",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::C_String[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_xsd_string"]],
        ["in", "in2", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["in", "in3", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getAssociatedNotificationSchemes"),
      "",
      "getAssociatedNotificationSchemes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["retval", "getAssociatedNotificationSchemesReturn", ["Jira4R::V2::RemoteScheme[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteScheme"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getAssociatedPermissionSchemes"),
      "",
      "getAssociatedPermissionSchemes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProjectRole", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProjectRole"]],
        ["retval", "getAssociatedPermissionSchemesReturn", ["Jira4R::V2::RemoteScheme[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteScheme"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getCustomFields"),
      "",
      "getCustomFields",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getCustomFieldsReturn", ["Jira4R::V2::RemoteField[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteField"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getSavedFilters"),
      "",
      "getSavedFilters",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getSavedFiltersReturn", ["Jira4R::V2::RemoteFilter[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteFilter"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getComments"),
      "",
      "getComments",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getCommentsReturn", ["Jira4R::V2::RemoteComment[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteComment"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "archiveVersion"),
      "",
      "archiveVersion",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["::SOAP::SOAPString"]],
        ["in", "in3", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getVersions"),
      "",
      "getVersions",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getVersionsReturn", ["Jira4R::V2::RemoteVersion[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteVersion"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "createProject"),
      "",
      "createProject",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["::SOAP::SOAPString"]],
        ["in", "in3", ["::SOAP::SOAPString"]],
        ["in", "in4", ["::SOAP::SOAPString"]],
        ["in", "in5", ["::SOAP::SOAPString"]],
        ["in", "in6", ["Jira4R::V2::RemotePermissionScheme", "http://beans.soap.rpc.jira.atlassian.com", "RemotePermissionScheme"]],
        ["in", "in7", ["Jira4R::V2::RemoteScheme", "http://beans.soap.rpc.jira.atlassian.com", "RemoteScheme"]],
        ["in", "in8", ["Jira4R::V2::RemoteScheme", "http://beans.soap.rpc.jira.atlassian.com", "RemoteScheme"]],
        ["retval", "createProjectReturn", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "addComment"),
      "",
      "addComment",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["Jira4R::V2::RemoteComment", "http://beans.soap.rpc.jira.atlassian.com", "RemoteComment"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getFieldsForEdit"),
      "",
      "getFieldsForEdit",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getFieldsForEditReturn", ["Jira4R::V2::RemoteField[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteField"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "addUserToGroup"),
      "",
      "addUserToGroup",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteGroup", "http://beans.soap.rpc.jira.atlassian.com", "RemoteGroup"]],
        ["in", "in2", ["Jira4R::V2::RemoteUser", "http://beans.soap.rpc.jira.atlassian.com", "RemoteUser"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "removeUserFromGroup"),
      "",
      "removeUserFromGroup",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteGroup", "http://beans.soap.rpc.jira.atlassian.com", "RemoteGroup"]],
        ["in", "in2", ["Jira4R::V2::RemoteUser", "http://beans.soap.rpc.jira.atlassian.com", "RemoteUser"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "logout"),
      "",
      "logout",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "logoutReturn", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "deleteProject"),
      "",
      "deleteProject",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "releaseVersion"),
      "",
      "releaseVersion",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["Jira4R::V2::RemoteVersion", "http://beans.soap.rpc.jira.atlassian.com", "RemoteVersion"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "deleteIssue"),
      "",
      "deleteIssue",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "addAttachmentsToIssue"),
      "",
      "addAttachmentsToIssue",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["Jira4R::V2::C_String[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_xsd_string"]],
        ["in", "in3", ["Jira4R::V2::Byte[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_xsd_base64Binary"]],
        ["retval", "addAttachmentsToIssueReturn", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getAttachmentsFromIssue"),
      "",
      "getAttachmentsFromIssue",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getAttachmentsFromIssueReturn", ["Jira4R::V2::RemoteAttachment[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteAttachment"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "hasPermissionToEditComment"),
      "",
      "hasPermissionToEditComment",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteComment", "http://beans.soap.rpc.jira.atlassian.com", "RemoteComment"]],
        ["retval", "hasPermissionToEditCommentReturn", ["::SOAP::SOAPBoolean"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "editComment"),
      "",
      "editComment",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteComment", "http://beans.soap.rpc.jira.atlassian.com", "RemoteComment"]],
        ["retval", "editCommentReturn", ["Jira4R::V2::RemoteComment", "http://beans.soap.rpc.jira.atlassian.com", "RemoteComment"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getFieldsForAction"),
      "",
      "getFieldsForAction",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["::SOAP::SOAPString"]],
        ["retval", "getFieldsForActionReturn", ["Jira4R::V2::RemoteField[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteField"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "progressWorkflowAction"),
      "",
      "progressWorkflowAction",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["::SOAP::SOAPString"]],
        ["in", "in3", ["Jira4R::V2::RemoteFieldValue[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteFieldValue"]],
        ["retval", "progressWorkflowActionReturn", ["Jira4R::V2::RemoteIssue", "http://beans.soap.rpc.jira.atlassian.com", "RemoteIssue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getIssueById"),
      "",
      "getIssueById",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getIssueByIdReturn", ["Jira4R::V2::RemoteIssue", "http://beans.soap.rpc.jira.atlassian.com", "RemoteIssue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getNotificationSchemes"),
      "",
      "getNotificationSchemes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getNotificationSchemesReturn", ["Jira4R::V2::RemoteScheme[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteScheme"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getPermissionSchemes"),
      "",
      "getPermissionSchemes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getPermissionSchemesReturn", ["Jira4R::V2::RemotePermissionScheme[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemotePermissionScheme"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "createPermissionScheme"),
      "",
      "createPermissionScheme",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["::SOAP::SOAPString"]],
        ["retval", "createPermissionSchemeReturn", ["Jira4R::V2::RemotePermissionScheme", "http://beans.soap.rpc.jira.atlassian.com", "RemotePermissionScheme"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "deletePermissionScheme"),
      "",
      "deletePermissionScheme",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "addPermissionTo"),
      "",
      "addPermissionTo",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemotePermissionScheme", "http://beans.soap.rpc.jira.atlassian.com", "RemotePermissionScheme"]],
        ["in", "in2", ["Jira4R::V2::RemotePermission", "http://beans.soap.rpc.jira.atlassian.com", "RemotePermission"]],
        ["in", "in3", ["Jira4R::V2::RemoteEntity", "http://beans.soap.rpc.jira.atlassian.com", "RemoteEntity"]],
        ["retval", "addPermissionToReturn", ["Jira4R::V2::RemotePermissionScheme", "http://beans.soap.rpc.jira.atlassian.com", "RemotePermissionScheme"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "deletePermissionFrom"),
      "",
      "deletePermissionFrom",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemotePermissionScheme", "http://beans.soap.rpc.jira.atlassian.com", "RemotePermissionScheme"]],
        ["in", "in2", ["Jira4R::V2::RemotePermission", "http://beans.soap.rpc.jira.atlassian.com", "RemotePermission"]],
        ["in", "in3", ["Jira4R::V2::RemoteEntity", "http://beans.soap.rpc.jira.atlassian.com", "RemoteEntity"]],
        ["retval", "deletePermissionFromReturn", ["Jira4R::V2::RemotePermissionScheme", "http://beans.soap.rpc.jira.atlassian.com", "RemotePermissionScheme"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getAllPermissions"),
      "",
      "getAllPermissions",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getAllPermissionsReturn", ["Jira4R::V2::RemotePermission[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemotePermission"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getIssueCountForFilter"),
      "",
      "getIssueCountForFilter",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getIssueCountForFilterReturn", ["::SOAP::SOAPLong"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getIssuesFromTextSearch"),
      "",
      "getIssuesFromTextSearch",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getIssuesFromTextSearchReturn", ["Jira4R::V2::RemoteIssue[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteIssue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getIssuesFromTextSearchWithProject"),
      "",
      "getIssuesFromTextSearchWithProject",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::C_String[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_xsd_string"]],
        ["in", "in2", ["::SOAP::SOAPString"]],
        ["in", "in3", ["::SOAP::SOAPInt"]],
        ["retval", "getIssuesFromTextSearchWithProjectReturn", ["Jira4R::V2::RemoteIssue[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteIssue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "deleteUser"),
      "",
      "deleteUser",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "updateGroup"),
      "",
      "updateGroup",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteGroup", "http://beans.soap.rpc.jira.atlassian.com", "RemoteGroup"]],
        ["retval", "updateGroupReturn", ["Jira4R::V2::RemoteGroup", "http://beans.soap.rpc.jira.atlassian.com", "RemoteGroup"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "deleteGroup"),
      "",
      "deleteGroup",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "refreshCustomFields"),
      "",
      "refreshCustomFields",
      [ ["in", "in0", ["::SOAP::SOAPString"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getProjectNoSchemes"),
      "",
      "getProjectNoSchemes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getProjectNoSchemesReturn", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getProjectsNoSchemes"),
      "",
      "getProjectsNoSchemes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getProjectsNoSchemesReturn", ["Jira4R::V2::RemoteProject[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteProject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "addVersion"),
      "",
      "addVersion",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["Jira4R::V2::RemoteVersion", "http://beans.soap.rpc.jira.atlassian.com", "RemoteVersion"]],
        ["retval", "addVersionReturn", ["Jira4R::V2::RemoteVersion", "http://beans.soap.rpc.jira.atlassian.com", "RemoteVersion"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "createProjectFromObject"),
      "",
      "createProjectFromObject",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]],
        ["retval", "createProjectFromObjectReturn", ["Jira4R::V2::RemoteProject", "http://beans.soap.rpc.jira.atlassian.com", "RemoteProject"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getSecuritySchemes"),
      "",
      "getSecuritySchemes",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["retval", "getSecuritySchemesReturn", ["Jira4R::V2::RemoteScheme[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteScheme"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getIssuesFromFilter"),
      "",
      "getIssuesFromFilter",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getIssuesFromFilterReturn", ["Jira4R::V2::RemoteIssue[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteIssue"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getComment"),
      "",
      "getComment",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPLong"]],
        ["retval", "getCommentReturn", ["Jira4R::V2::RemoteComment", "http://beans.soap.rpc.jira.atlassian.com", "RemoteComment"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "createGroup"),
      "",
      "createGroup",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["in", "in2", ["Jira4R::V2::RemoteUser", "http://beans.soap.rpc.jira.atlassian.com", "RemoteUser"]],
        ["retval", "createGroupReturn", ["Jira4R::V2::RemoteGroup", "http://beans.soap.rpc.jira.atlassian.com", "RemoteGroup"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getComponents"),
      "",
      "getComponents",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getComponentsReturn", ["Jira4R::V2::RemoteComponent[]", "http://localhost:8080/rpc/soap/jirasoapservice-v2", "ArrayOf_tns1_RemoteComponent"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ],
    [ XSD::QName.new("http://soap.rpc.jira.atlassian.com", "getGroup"),
      "",
      "getGroup",
      [ ["in", "in0", ["::SOAP::SOAPString"]],
        ["in", "in1", ["::SOAP::SOAPString"]],
        ["retval", "getGroupReturn", ["Jira4R::V2::RemoteGroup", "http://beans.soap.rpc.jira.atlassian.com", "RemoteGroup"]] ],
      { :request_style =>  :rpc, :request_use =>  :encoded,
        :response_style => :rpc, :response_use => :encoded,
        :faults => {"Jira4R::V2::RemoteValidationException"=>{:name=>"RemoteValidationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteAuthenticationException"=>{:name=>"RemoteAuthenticationException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemoteException"=>{:name=>"RemoteException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}, "Jira4R::V2::RemotePermissionException"=>{:name=>"RemotePermissionException", :ns=>"http://localhost:8080/rpc/soap/jirasoapservice-v2", :encodingstyle=>"http://schemas.xmlsoap.org/soap/encoding/", :use=>"encoded", :namespace=>"http://localhost:8080/rpc/soap/jirasoapservice-v2"}} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = DefaultMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = DefaultMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

end
